Repository fipl-hse/2020-2-level-labs, pull requests merged in 2020-10, with the labels that each got.

#70 [LAB 2] Tests for score 8 functions, additions to score 4&6 functions
  config/lab_2/target_tests_6.txt
  config/lab_2/target_tests_8.txt
  lab_2/accumulate_diff_stats_test.py
  lab_2/calculate_plagiarism_score_test.py
  lab_2/calculate_text_plagiarism_score_test.py
  lab_2/create_zero_matrix_test.py
  lab_2/find_diff_in_sentences_test.py
  lab_2/find_lcs_length_test.py
  lab_2/find_lcs_test.py
Labels: WIP

#16 Laboratory work #1, Karabasova Julia - 19FPL2
  lab_1/main.py
  lab_1/start.py
  lab_1/target_score.txt
Labels: Done

#108 Laboratory work #2, Galkina Ksenia - 19FPL2
  lab_2/calculate_text_plagiarism_score_test.py
  lab_2/find_lcs_length_optimized_test.py
  lab_2/main.py
  lab_2/start.py
  lab_2/target_score.txt
  lab_2/tokenize_big_file_test.py
Labels: Done, Review required
